### ISSUE TITLE
Suggestion: Using Git-Flow 

### ISSUE THREAD

**Issue by cmirdesouza** [orgtre/anki-editor#11]
It is simple to use and learn. It has integration with magit and gives a better structure for collaboration. 
What do you think? Other alternatives are welcomed.

**Comment by orgtre** [comment]
I'm not sure what you mean. [This](https://github.com/petervanderdoes/gitflow-avh)? I think it would just complicate development.

**Comment by orgtre** [comment]
The anki-editor repo had this kind of workflow before, but we decided to abandon it (see #3). anki-editor is such a small project that all this just makes things slower. For example, a lot of features would sit forever on the develop branch with most people not knowing about it. Users then often wasted time reimplementing stuff that was already in develop. I'd say it is better to push new feature directly into main, since then a larger user based will be involved with testing, reporting bugs, issues etc. and if something breaks its not a big thing in this kind of project. Users that want a more stable experience can just update to tags, which we'll reintroduce, I'd say, like in the original repo.

That said, feel free to use this kind of structure in your forks (I also use local branches when trying out new features). All you need to remember is to then submit your pull requests to master here. If we end up trying to implement a larger new feature we can still discuss having a separate branch here for it of course.

**Comment by cmirdesouza** [comment]
It makes sense, thanks for the response.
I don't know how tags work, can you give me some link?

**Comment by orgtre** [comment]
Looks like the original repo didn't use git tags actually, just separately maintained version numbers... [Here](https://git-scm.com/book/en/v2/Git-Basics-Tagging) and [here](https://docs.github.com/en/rest/git/tags), and [an example](https://github.com/ohare93/brain-brew/tags).

**Comment by cmirdesouza** [comment]
Thanks for the resources, i was mixing tags and releases (it seems to have some differences).
