### ISSUE TITLE
ol-anki shares functionality with anki-editor. Any chance to consolidate the common functionality in a separate package?

### ISSUE THREAD

**Issue by lordnik22** [orgtre/anki-editor#15]
Hi orgtre

I originally found louietan-repo but saw in the issues you took over the steering wheel. Thanks for maintaining anki-editor! 

I just implemented a basic "ol-anki" which allows the creation of org-links pointing to anki decks: https://github.com/lordnik22/ol-anki

In that repo I copied over some basic functionality from anki-editor. Namely the request-interface to anki-connect.
This consists of following functions:
- anki-editor-anki-connect-listening-address
- anki-editor-anki-connect-listening-port
- anki-editor--anki-connect-invoke-result
- anki-editor--anki-connect-action
- anki-editor--anki-connect-invoke
- anki-editor-deck-names

A minor problem for me is that I don't want a dependency to the whole anki-editor but only to the "anki-connect-request-interface". What do you think about the idea making a separate package consisting only the interface to anki connect?

Best regards
lordnik22

**Comment by orgtre** [comment]
Hi lordnik22, it's great you're developing org/Anki stuff! In principle I'm open to your suggestion. I've also been thinking about making the anki-connect interface a separate package, so that one can optionally use the sql interface provided [here](https://github.com/orgtre/ankiorg) instead.

However, given that the number of lines of code you need is quite small, I think the better option for now is to just copy over the functions like you did and changing the prefix to ol-anki (so that there is no conflict when users use both packages). Like this we can both make changes in the interface without having to worry about breaking each others packages (something I am at least [considering](https://github.com/FooSoft/anki-connect/issues/358)). 

Note also that all the functions you list have been renamed (and some have changed too). The anki-connect interface would be everything in the ";;; AnkiConnect" section of the code and this only partially overlaps with what you need.

Right now I'm also not sure how package managers can automatically handle dependencies (of packages) that are not registered on MELPA or the like (?).

**Comment by lordnik22** [comment]
Hi orgtre

Alright than, I will postpone that until there may be a unified anki-connect-interface in the future. 

For now, I just use the newest version (your version) of the copied functions and prefix them with ol-anki.
With some minor adjustments made everything works as before :P. I don't think you need to inform me about any future changes on these.

I'm also not sure about the dependency management of each package manager. I though Emacs Cask may be an approach trying to solve this problem but the doc isn't clear to me and haven't used it since a while. I only used it for local development stuff, so I think the package manager doesn't care about the cask-file. Haven't dig very deep on that topic, so - just an idea :)
