### ISSUE TITLE
some way to bypass character escaping?

### ISSUE THREAD

**Issue by FinnFrotscher** [orgtre/anki-editor#18]
The note i want to send contains some HTML that I want Anki to consume as HTML. But when I sync the note, all the special characters get escaped. any idea how I can bypass that?

Note in Org:
<img width="396" alt="Screenshot 2023-03-08 at 23 59 31" src="https://user-images.githubusercontent.com/11148454/223870647-4bd97011-6b64-44d4-bad1-5cc66b38e297.png">

Same note in Anki:
<img width="367" alt="Screenshot 2023-03-08 at 23 59 42" src="https://user-images.githubusercontent.com/11148454/223870667-456d71a5-4d54-4637-a67a-cac7d8984a0a.png">

**Comment by orgtre** [comment]
You can do this by adding `:ANKI_FORMAT: nil` into the property drawer of the note subtree before exporting. The command `anki-editor-toggle-format` can be used for this. [One of the examples](https://github.com/orgtre/anki-editor/blob/master/examples.org#back) also illustrates this.

That said, one of the selling-points of anki-editor is that it allows you to use the convenient Org markup language for formatting instead of bothering with html.
